version: '3.5'

services:
  db:
    # MariaDB for RPI
    image: jsurf/rpi-raspbian:latest
    restart: unless-stopped
    environment: 
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=economy
      - MYSQL_PASSWORD=economy
      - MYSQL_DATABASE=economy
    volumes:
      - /home/node/docker/mysql:/var/lib/mysql

  budget-api:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8080:8080
    networks: 
      - budget
      - default

networks: 
  budget:
    name: budget_network