version: '3.1'

services:
  # nginx:
  #   image: nginx:latest
  #   restart: unless-stopped
  #   volumes:
  #     - ./data/nginx:/etc/nginx/conf.d
  #     - /etc/letsencrypt/live/dasifor.xyz/:/ssl/
  #   ports:
  #     - "80:80"
  #     - "443:443"
  db:
    image: mariadb
    restart: unless-stopped
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=economy
      - MYSQL_PASSWORD=economy
      - MYSQL_DATABASE=economy
    volumes:
      - /home/node/docker/mysql:/var/lib/mysql

  budget-api:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8080:8080