version: '3.1'

services:


  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - /var/lib/mysql:/var/lib/mysql

  budget-api:
    image: budget-api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8080:8080