version: '3.1'

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - /etc/letsencrypt/live/dasifor.xyz/:/ssl/
    ports:
      - "80:80"
      - "443:443"    
  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - /home/node/docker/mysql:/var/lib/mysql

  budget-api:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
      - nginx
    ports:
      - 8080:8080

  
